/* recetas.js — corpus. Porción A = menor, porción B = 20 % mayor (proteína y almidón).
   Sin horno · sin gluten · sin lácteos · sin legumbres · sin pimentón · sin crucíferas ·
   sin mariscos ni salsa de pescado · sin limón · sin sopas ni nada húmedo · sin recalentados ·
   sin ácido en el desayuno —tomate, vinagre, cítrico— porque romper el ayuno con ácido
   le dispara el reflujo.
   d:1 = despensa, se compra una vez y dura meses. d:0 = tienda, fruver o carnicería del barrio. */

window.AJUSTES = {
  humedo:     ["Quedó húmedo",        "Seca la proteína con papel antes de que toque el sartén y cocínala en dos tandas. El sartén lleno suda en vez de dorar: esa es toda la diferencia."],
  crujiente:  ["Faltó crujiente",     "Sartén precalentado dos minutos largos, fuego alto, y no muevas nada durante el primer minuto. La costra se forma en contacto quieto, no revolviendo."],
  salado:     ["Muy salado",          "El tamari sala mucho más que la sal. Usa la mitad y ajusta al final, con el fuego apagado."],
  soso:       ["Le faltó sabor",      "Sube el aceite de ajo y termina con vinagre de arroz fuera del fuego. El ácido al final es lo que despierta el plato."],
  demorada:   ["Se demoró demasiado", "Pica todo antes de prender el fuego. El salteado son ocho minutos; lo demás es picar."],
  proteina:   ["Quedé con hambre",    "Sube 30 g de proteína por porción y deja el vegetal igual. Si aun así, añade medio aguacate."],
  pesada:     ["Me cayó pesada",      "Baja el aceite a la mitad y cambia la proteína por pollo o tilapia la próxima vez."],
  consegui:   ["No conseguí algo",    "Anota cuál abajo y te lo cambio por algo de tienda de barrio en la siguiente sugerencia."]
};

window.RECETAS = [
{id:"pollo-jengibre", mom:"ambos", n:"Pollo al jengibre con cebolla larga", min:30, base:"pollo", tag:["sartén","rápido"],
 porque:"Jengibre y pollo: antiinflamatorio y de las proteínas de purina más baja que hay. La cebolla larga entra solo con la parte verde.",
 ing:[{i:"Pechuga de pollo en tiras",a:150,b:180,u:"g"},{i:"Jengibre fresco rallado",a:15,b:15,u:"g"},
      {i:"Cebolla larga, parte verde",a:2,b:2,u:"tallos"},{i:"Zanahoria en bastones",a:1,b:1,u:"und"},
      {i:"Dientes de ajo",a:3,b:3,u:"und"},{i:"Tamari",a:2,b:2,u:"cda",d:1},
      {i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},{i:"Miel",a:1,b:1,u:"cdta"},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Pon el arroz a cocinar primero; todo lo demás dura menos que él.",
        "Dora los dientes de ajo enteros en el aceite a fuego medio hasta que estén dorados y retíralos. Ese aceite es la base.",
        "Sube a fuego alto. Echa el pollo seco y no lo muevas un minuto entero.",
        "Añade zanahoria y jengibre, saltea dos minutos: la zanahoria debe quedar firme.",
        "Tamari, vinagre y miel fuera del fuego. Revuelve y termina con la cebolla larga verde cruda encima."],
 crispy:"El pollo se seca con papel antes de entrar. Sin eso no dora, se cuece."},

{id:"cerdo-shogayaki", mom:"ambos", n:"Cerdo al jengibre estilo shogayaki", min:25, base:"cerdo", tag:["sartén","rápido"],
 porque:"Corte magro y porción corta. El cerdo no se elimina de la carta, se modera.",
 ing:[{i:"Lomo de cerdo en láminas finas",a:120,b:150,u:"g"},{i:"Jengibre rallado",a:20,b:20,u:"g"},
      {i:"Tamari",a:2,b:2,u:"cda",d:1},{i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},
      {i:"Miel",a:1,b:1,u:"cdta"},{i:"Rúgula",a:1,b:1,u:"puñado"},
      {i:"Aceite de oliva",a:1,b:1,u:"cda"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Mezcla jengibre, tamari, vinagre y miel en un pocillo.",
        "Sartén bien caliente, láminas de cerdo en una sola capa, minuto y medio por lado.",
        "Apaga el fuego y echa la salsa: se evapora sola con el calor del sartén.",
        "Sirve sobre el arroz con la rúgula cruda al lado."],
 crispy:"Una capa sola en el sartén. Amontonado suelta agua y se hierve.",
 ojo:"Porción de cerdo deliberadamente corta. No la subas aunque quede con hambre: suma aguacate."},

{id:"res-apio", mom:"almuerzo", n:"Res desmechada salteada con apio", min:40, base:"res", tag:["sartén"],
 porque:"Res desmechada una vez por semana como máximo, y en porción medida: es la que más purina aporta de las que quedan.",
 ing:[{i:"Carne de res para desmechar (ya cocida)",a:120,b:145,u:"g"},{i:"Apio en bastones",a:3,b:3,u:"tallos"},
      {i:"Zanahoria en juliana",a:1,b:1,u:"und"},{i:"Dientes de ajo",a:3,b:3,u:"und"},
      {i:"Tamari",a:2,b:2,u:"cda",d:1},{i:"Aceite de ajonjolí",a:1,b:1,u:"cdta",d:1},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Aceite de oliva",a:2,b:2,u:"cda"},
      {i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Aceite de ajo: dora los dientes enteros y retíralos.",
        "Fuego alto. Carne desmechada sin mover, dos minutos, hasta que los bordes se tuesten.",
        "Apio y zanahoria, dos minutos más. Tienen que sonar al morderlos.",
        "Tamari fuera del fuego, aceite de ajonjolí y ajonjolí tostado encima."],
 crispy:"El punto está en tostar los bordes de la carne. Si la mueves, no pasa."},

{id:"pollo-teriyaki", mom:"ambos", n:"Pollo teriyaki de sartén", min:30, base:"pollo", tag:["plancha"],
 porque:"Teriyaki casero: la salsa embotellada trae trigo y jarabe de maíz, y los dos están fuera de esta carta.",
 ing:[{i:"Muslo de pollo deshuesado sin piel",a:160,b:190,u:"g"},{i:"Tamari",a:3,b:3,u:"cda",d:1},
      {i:"Miel",a:1,b:1,u:"cda"},{i:"Jengibre rallado",a:10,b:10,u:"g"},
      {i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},{i:"Cebolla larga verde",a:1,b:1,u:"tallo"},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"},
      {i:"Aceite de oliva",a:1,b:1,u:"cda"}],
 pasos:["Sartén caliente, pollo con el lado liso abajo, seis minutos sin tocarlo.",
        "Voltea, cuatro minutos más.",
        "Baja el fuego, echa tamari, miel, jengibre y vinagre. Deja que espese un minuto bañando el pollo.",
        "Corta en tiras, sirve sobre arroz con ajonjolí y cebolla larga."],
 crispy:"Seis minutos quieto del primer lado. Ahí se hace la costra."},

{id:"pollo-mani", mom:"ambos", n:"Pollo salteado con maní y tamari", min:30, base:"pollo", tag:["sartén"],
 porque:"El maní aporta grasa buena y textura; es de las semillas que ya te gustan.",
 ing:[{i:"Pechuga en cubos",a:150,b:180,u:"g"},{i:"Maní tostado sin sal",a:30,b:35,u:"g"},
      {i:"Apio en cubos",a:2,b:2,u:"tallos"},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Dientes de ajo",a:3,b:3,u:"und"},{i:"Tamari",a:2,b:2,u:"cda",d:1},
      {i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},{i:"Maizena",a:1,b:1,u:"cda"},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Revuelca los cubos de pollo en la fécula: esa capa es la que queda crocante.",
        "Aceite de ajo, retira los dientes.",
        "Pollo a fuego alto sin mover dos minutos, voltea y dos más.",
        "Apio y maní, un minuto. Tamari y vinagre fuera del fuego, cebolla larga encima."],
 crispy:"La fécula seca es el truco. Si el pollo está mojado, se apelmaza."},

{id:"tilapia-sesamo", mom:"cena", n:"Tilapia en cubos con ajonjolí", min:25, base:"pescado", tag:["sartén","rápido"],
 porque:"Pescado suave, sin el sabor fuerte que rechazas, y de las proteínas de menor purina.",
 ing:[{i:"Filete de tilapia en cubos",a:170,b:200,u:"g"},{i:"Maizena",a:2,b:2,u:"cda"},
      {i:"Ajonjolí",a:2,b:2,u:"cda"},{i:"Jengibre rallado",a:10,b:10,u:"g"},
      {i:"Tamari",a:1,b:1,u:"cda",d:1},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Seca los cubos muy bien y pásalos por fécula mezclada con el ajonjolí.",
        "Sartén caliente, cubos separados, dos minutos por cara sin moverlos.",
        "Fuera del fuego: jengibre, tamari y cebolla larga.",
        "Sirve de inmediato; el pescado pierde el crocante en minutos."],
 crispy:"Separados en el sartén. Juntos se pegan y se deshacen."},

{id:"pavo-espinaca", mom:"cena", n:"Pavo salteado con espinaca y aceite de ajo", min:25, base:"pavo", tag:["sartén","rápido"],
 porque:"Pavo es la proteína de purina más baja de todas. La espinaca aporta folato y nitratos, y sus purinas vegetales no cuentan como las animales.",
 ing:[{i:"Pechuga de pavo en tiras",a:150,b:180,u:"g"},{i:"Espinaca fresca",a:150,b:150,u:"g"},
      {i:"Dientes de ajo",a:4,b:4,u:"und"},{i:"Tamari",a:1,b:1,u:"cda",d:1},
      {i:"Aceite de ajonjolí",a:1,b:1,u:"cdta",d:1},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Aceite de ajo y retira los dientes.",
        "Pavo a fuego alto, tres minutos, sin amontonar.",
        "Espinaca de golpe, treinta segundos: solo hasta que baje de volumen.",
        "Fuera del fuego, tamari, aceite de ajonjolí y ajonjolí tostado."],
 crispy:"La espinaca entra al final y sale rápido; pasada de fuego suelta toda el agua."},

{id:"karaage", mom:"almuerzo", n:"Pollo crocante estilo karaage, en sartén", min:35, base:"pollo", tag:["crispy"],
 porque:"Lo frito en sartén honda reemplaza el horno que no quieres prender. Es el plato más crocante del recetario.",
 ing:[{i:"Muslo de pollo en trozos",a:170,b:200,u:"g"},{i:"Tamari",a:2,b:2,u:"cda",d:1},
      {i:"Jengibre rallado",a:15,b:15,u:"g"},{i:"Maizena",a:4,b:4,u:"cda"},
      {i:"Aceite para freír",a:1,b:1,u:"taza"},{i:"Rúgula",a:1,b:1,u:"puñado"},
      {i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Marina el pollo veinte minutos en tamari y jengibre. Mientras, cocina el arroz.",
        "Escurre bien y pasa cada trozo por fécula, apretando.",
        "Aceite a fuego medio-alto, dos dedos de hondo. Fríe en tandas, cuatro minutos.",
        "Saca sobre rejilla, nunca sobre papel: el vapor abajo lo ablanda."],
 crispy:"Rejilla, no papel. Y en dos tandas, para que el aceite no baje de temperatura.",
 ojo:"El único plato frito de la carta. Una vez por semana, no más."},

{id:"cerdo-maracuya", mom:"ambos", n:"Cerdo agridulce de maracuyá", min:30, base:"cerdo", tag:["sartén"],
 porque:"El agridulce clásico lleva limón o piña. El maracuyá te gusta y hace el mismo trabajo.",
 ing:[{i:"Lomo de cerdo en cubos",a:120,b:150,u:"g"},{i:"Pulpa de maracuyá",a:3,b:3,u:"und"},
      {i:"Miel",a:1,b:1,u:"cda"},{i:"Tamari",a:2,b:2,u:"cda",d:1},
      {i:"Maizena",a:2,b:2,u:"cda"},{i:"Zanahoria en bastones",a:1,b:1,u:"und"},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Cuela la pulpa de maracuyá; mézclala con miel y tamari.",
        "Pasa el cerdo por fécula y dóralo a fuego alto, sin mover, tres minutos.",
        "Zanahoria dos minutos.",
        "Salsa al final, un minuto de fuego para que brille y espese."],
 crispy:"La fécula en la carne también espesa la salsa. No necesitas nada más."},
{id:"huevo-tomate", mom:"cena", n:"Huevo y tomate salteados, versión seca", min:20, base:"huevo", tag:["sartén","rápido","económico"],
 porque:"El clásico chino, ajustado: el original queda caldoso y aquí va escurrido y firme. De cena, nunca de desayuno.",
 ing:[{i:"Huevos",a:3,b:4,u:"und"},{i:"Tomate maduro en gajos",a:2,b:2,u:"und"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Tamari",a:1,b:1,u:"cda",d:1},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Saca las semillas y el agua del tomate con una cuchara. Ese paso es el que cambia la textura.",
        "Bate los huevos y cuájalos en sartén caliente hasta que estén firmes, no cremosos. Sácalos.",
        "Tomate a fuego alto dos minutos, hasta que pierda el agua.",
        "Devuelve el huevo, tamari, cebolla larga y fuera."],
 crispy:"Huevo firme con borde dorado. Si queda baboso, es fuego bajo.",
 ojo:"De cena o de almuerzo, nunca en ayunas: el tomate en ayunas te dispara el reflujo."},

{id:"cucayo-huevo", mom:"almuerzo", n:"Arroz con cucayo y huevo crocante", min:30, base:"huevo", tag:["cucayo","económico","seguro"],
 porque:"Tu comida segura, que resulta ser la misma técnica del nurungji coreano. El punto de partida cuando no hay ánimo de experimentar.",
 ing:[{i:"Arroz blanco crudo",a:70,b:85,u:"g"},{i:"Huevos",a:2,b:3,u:"und"},
      {i:"Dientes de ajo",a:3,b:3,u:"und"},{i:"Cebolla larga verde",a:1,b:1,u:"tallo"},
      {i:"Tamari",a:1,b:1,u:"cda",d:1},{i:"Aceite de oliva",a:3,b:3,u:"cda"},
      {i:"Aguacate",a:0.5,b:0.5,u:"und"}],
 pasos:["Cocina el arroz y déjalo reposar destapado diez minutos para que se seque.",
        "Aceite de ajo en sartén ancho; retira los dientes.",
        "Extiende el arroz en capa delgada y déjalo quieto de seis a ocho minutos a fuego medio. No lo toques: el cucayo se está formando.",
        "Aparte, huevos en aceite bien caliente hasta que el borde quede tostado.",
        "Levanta el arroz con espátula, tamari, huevo encima, cebolla larga y aguacate al lado."],
 crispy:"Capa delgada, fuego medio y paciencia. El cucayo se oye antes de verse."},

{id:"bibimbap", mom:"almuerzo", n:"Bibimbap de sartén, sin pimentón", min:45, base:"res", tag:["cucayo"],
 porque:"El bibimbap lleva gochujang, que es pasta de pimentón. Aquí el sabor lo carga el miso con tamari y queda igual de redondo.",
 ing:[{i:"Carne de res desmechada",a:110,b:135,u:"g"},{i:"Arroz blanco crudo",a:70,b:85,u:"g"},
      {i:"Espinaca",a:100,b:100,u:"g"},{i:"Zanahoria en juliana",a:1,b:1,u:"und"},
      {i:"Huevos",a:1,b:1,u:"und"},{i:"Miso",a:1,b:1,u:"cda",d:1},
      {i:"Tamari",a:1,b:1,u:"cda",d:1},{i:"Aceite de ajonjolí",a:1,b:1,u:"cdta",d:1},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Dientes de ajo",a:4,b:4,u:"und"},
      {i:"Aceite de oliva",a:3,b:3,u:"cda"}],
 pasos:["Cocina el arroz. Mezcla miso, tamari y aceite de ajonjolí: esa es la salsa.",
        "Aceite de ajo. Saltea por separado y rápido la espinaca y la zanahoria; resérvalas en montoncitos.",
        "Dora la carne desmechada hasta que los bordes se tuesten.",
        "Arroz en capa delgada en el sartén, seis minutos quieto para el cucayo.",
        "Monta encima los montoncitos por separado, el huevo frito de borde crocante en el centro y la salsa aparte."],
 crispy:"Cada vegetal por separado y al ojo: juntos sueltan agua y se vuelve un revuelto."},

{id:"arroz-frito-pollo", mom:"almuerzo", n:"Arroz frito con pollo y cebolla larga", min:25, base:"pollo", tag:["sartén","rápido","económico"],
 porque:"Resuelve el arroz que sobró de ayer sin que sea un recalentado: se refríe a fuego alto y cambia de plato.",
 ing:[{i:"Arroz blanco cocido y frío",a:180,b:220,u:"g"},{i:"Pechuga en cubos",a:140,b:170,u:"g"},
      {i:"Huevos",a:1,b:2,u:"und"},{i:"Cebolla larga verde",a:3,b:3,u:"tallos"},
      {i:"Zanahoria en cubitos",a:1,b:1,u:"und"},{i:"Dientes de ajo",a:3,b:3,u:"und"},
      {i:"Tamari",a:2,b:2,u:"cda",d:1},{i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["El arroz tiene que estar frío y suelto. Tibio se apelmaza.",
        "Aceite de ajo, retira los dientes. Cuaja el huevo firme y sácalo.",
        "Pollo a fuego alto tres minutos, luego zanahoria dos.",
        "Arroz de golpe, extendido, dos minutos sin mover para que se tueste por debajo.",
        "Devuelve el huevo, tamari por el borde del sartén, cebolla larga y fuera."],
 crispy:"Tamari por el borde caliente, no encima del arroz: se evapora y tuesta en vez de mojar."},

{id:"arroz-pastrami", mom:"almuerzo", n:"Arroz frito con pastrami y huevo", min:25, base:"cerdo", tag:["sartén","rápido"],
 porque:"Tu sánduche de pastrami convertido en salteado. El pastrami es carne curada: porción corta y no más de una vez por semana.",
 ing:[{i:"Arroz blanco cocido y frío",a:180,b:220,u:"g"},{i:"Pastrami en tiras",a:90,b:110,u:"g"},
      {i:"Huevos",a:2,b:2,u:"und"},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Dientes de ajo",a:3,b:3,u:"und"},{i:"Tamari",a:1,b:1,u:"cda",d:1},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Dora el pastrami solo, sin aceite, hasta que los bordes se ricen. Sácalo.",
        "En esa misma grasa dora el ajo y retíralo.",
        "Huevo firme, sácalo. Arroz extendido dos minutos sin mover.",
        "Junta todo, poquísimo tamari (el pastrami ya es salado) y cebolla larga."],
 crispy:"Los bordes rizados del pastrami son el crujiente del plato.",
 ojo:"Embutido curado: alto en sodio y alto en purinas. Semanal, no más."},

{id:"arroz-atun", mom:"cena", n:"Arroz con atún y ajonjolí", min:20, base:"pescado", tag:["rápido","económico","despensa"],
 porque:"El plato de emergencia: todo sale de la despensa. Atún en porción moderada por purinas.",
 ing:[{i:"Atún enlatado en agua, escurrido",a:120,b:150,u:"g"},{i:"Arroz blanco crudo",a:70,b:85,u:"g"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Ajonjolí",a:2,b:2,u:"cda"},
      {i:"Aceite de ajonjolí",a:1,b:1,u:"cdta",d:1},{i:"Tamari",a:1,b:1,u:"cda",d:1},
      {i:"Aguacate",a:0.5,b:0.5,u:"und"},{i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Cocina el arroz y sécalo destapado.",
        "Escurre el atún hasta que no suelte nada y dóralo en sartén caliente tres minutos sin moverlo.",
        "Arroz extendido en el sartén, cuatro minutos para el cucayo.",
        "Monta atún, aguacate, tamari, aceite de ajonjolí y mucho ajonjolí tostado."],
 crispy:"Atún bien escurrido y quieto en el sartén: se tuesta en hebras.",
 ojo:"Atún máximo dos veces por semana entre los dos."},

{id:"nurungji-pollo", mom:"almuerzo", n:"Cucayo con pollo desmechado y aceite de ajo", min:35, base:"pollo", tag:["cucayo","económico"],
 porque:"Todo el sabor viene del aceite de ajo, sin el ajo. Es el plato que prueba que la técnica funciona.",
 ing:[{i:"Pechuga cocida y desmechada",a:150,b:180,u:"g"},{i:"Arroz blanco crudo",a:70,b:85,u:"g"},
      {i:"Dientes de ajo",a:6,b:6,u:"und"},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Tamari",a:2,b:2,u:"cda",d:1},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Aceite de oliva",a:4,b:4,u:"cda"}],
 pasos:["Dora los seis dientes en el aceite a fuego bajo, ocho minutos, hasta dorados. Retíralos; quien tolere el ajo entero puede comérselos aparte.",
        "Saltea el pollo desmechado en ese aceite hasta que las hebras se tuesten.",
        "Sácalo, extiende el arroz y déjalo quieto siete minutos.",
        "Junta, tamari, ajonjolí y cebolla larga."],
 crispy:"Hebras de pollo tostadas más cucayo: dos crujientes distintos en el mismo plato."},

{id:"fideos-pollo", mom:"almuerzo", n:"Fideos de arroz salteados con pollo", min:30, base:"pollo", tag:["fideos","sartén"],
 porque:"Versión del pad see ew sin salsa de pescado ni brócoli. El fideo de arroz reemplaza el trigo sin que se note.",
 ing:[{i:"Fideos de arroz anchos",a:70,b:90,u:"g",d:1},{i:"Pechuga en tiras",a:150,b:180,u:"g"},
      {i:"Espinaca",a:100,b:100,u:"g"},{i:"Huevos",a:1,b:1,u:"und"},
      {i:"Dientes de ajo",a:3,b:3,u:"und"},{i:"Tamari",a:3,b:3,u:"cda",d:1},
      {i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},{i:"Miel",a:1,b:1,u:"cdta"},
      {i:"Aceite de oliva",a:3,b:3,u:"cda"}],
 pasos:["Hidrata los fideos en agua caliente hasta que flexionen sin romperse. Escúrrelos muy bien.",
        "Aceite de ajo, retira los dientes. Pollo a fuego alto tres minutos.",
        "Huevo al lado, cuájalo firme y revuelve.",
        "Fideos escurridos, extendidos, dos minutos sin mover para que se tuesten.",
        "Tamari, vinagre y miel por el borde. Espinaca al final, treinta segundos."],
 crispy:"Fideos escurridos hasta que no goteen, y quietos en el sartén. Mojados se vuelven engrudo."},

{id:"fideos-res", mom:"almuerzo", n:"Fideos de arroz con res y apio", min:30, base:"res", tag:["fideos","sartén"],
 porque:"El apio da el crujido que el fideo no tiene. Porción de res medida.",
 ing:[{i:"Fideos de arroz",a:70,b:90,u:"g",d:1},{i:"Res en tiras finas",a:110,b:135,u:"g"},
      {i:"Apio en bastones",a:3,b:3,u:"tallos"},{i:"Zanahoria en juliana",a:1,b:1,u:"und"},
      {i:"Dientes de ajo",a:3,b:3,u:"und"},{i:"Tamari",a:3,b:3,u:"cda",d:1},
      {i:"Aceite de ajonjolí",a:1,b:1,u:"cdta",d:1},{i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Hidrata y escurre los fideos.",
        "Aceite de ajo. Res a fuego muy alto, dos minutos, sin mover.",
        "Apio y zanahoria, dos minutos: firmes.",
        "Fideos, tamari por el borde, aceite de ajonjolí al final."],
 crispy:"El apio entra tarde y sale crujiente. Si se ablanda, entró muy temprano."},

{id:"fideos-crujientes", mom:"almuerzo", n:"Fideos crujientes con pollo y maní", min:35, base:"pollo", tag:["fideos","crispy"],
 porque:"Fideo frito en nido: la textura más crocante que se puede lograr sin horno.",
 ing:[{i:"Fideos de arroz finos",a:60,b:75,u:"g",d:1},{i:"Pechuga en tiras",a:150,b:180,u:"g"},
      {i:"Maní tostado",a:30,b:35,u:"g"},{i:"Cebolla larga verde",a:3,b:3,u:"tallos"},
      {i:"Zanahoria en juliana",a:1,b:1,u:"und"},{i:"Tamari",a:2,b:2,u:"cda",d:1},
      {i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},{i:"Aceite para freír",a:0.5,b:0.5,u:"taza"}],
 pasos:["Fríe un puñado de fideos secos, sin hidratar, en aceite caliente: inflan en segundos. Saca a rejilla.",
        "En dos cucharadas de ese aceite saltea el pollo, tres minutos.",
        "Zanahoria dos minutos, tamari y vinagre fuera del fuego.",
        "Sirve el salteado sobre el nido de fideos, con maní y cebolla larga. Monta al momento de comer."],
 crispy:"Los fideos se montan al final. Si los mezclas antes, se ablandan en un minuto."},

{id:"fideos-pepino", mom:"cena", n:"Fideos fríos con pepino y ajonjolí", min:20, base:"veg", tag:["fideos","rápido","calor"],
 porque:"Para los días de calor. Fríos pero no húmedos: la salsa va apenas para untar.",
 ing:[{i:"Fideos de arroz finos",a:70,b:90,u:"g",d:1},{i:"Pepino sin piel ni semillas, en bastones",a:1,b:1,u:"und"},
      {i:"Pechuga cocida desmechada",a:140,b:170,u:"g"},{i:"Ajonjolí",a:2,b:2,u:"cda"},
      {i:"Aceite de ajonjolí",a:1,b:1,u:"cda",d:1},{i:"Tamari",a:2,b:2,u:"cda",d:1},
      {i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},{i:"Maní tostado",a:25,b:30,u:"g"}],
 pasos:["Cocina los fideos, pásalos por agua fría y escúrrelos muy bien.",
        "Mezcla tamari, vinagre y aceite de ajonjolí: solo dos cucharadas en total, no más.",
        "Revuelve fideos, pollo y pepino con esa mezcla.",
        "Maní y ajonjolí por encima, generoso."],
 crispy:"Maní y pepino son el crujido. La salsa unta, no empapa."},

{id:"yakitori", mom:"ambos", n:"Pinchos de pollo yakitori", min:35, base:"pollo", tag:["plancha"],
 porque:"Sartén-plancha en vez de parrilla. El tamari con miel caramela igual.",
 ing:[{i:"Muslo de pollo en cubos",a:160,b:190,u:"g"},{i:"Cebolla larga, parte blanca y verde",a:3,b:3,u:"tallos"},
      {i:"Tamari",a:3,b:3,u:"cda",d:1},{i:"Miel",a:1,b:1,u:"cda"},
      {i:"Jengibre rallado",a:10,b:10,u:"g"},{i:"Palillos de pincho",a:4,b:5,u:"und"},
      {i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Arma los pinchos alternando pollo y trozos de cebolla larga.",
        "Sartén-plancha bien caliente, sin aceite si el muslo tiene grasa. Tres minutos por cara.",
        "Mezcla tamari, miel y jengibre. Pincela en los últimos dos minutos y deja que se caramele.",
        "Sirve con el arroz."],
 crispy:"La salsa va al final. Desde el principio se quema antes de que el pollo esté hecho."},

{id:"pechuga-platano", mom:"cena", n:"Pechuga con plátano maduro y aguacate", min:30, base:"pollo", tag:["plancha","seguro"],
 porque:"Es uno de tus cinco platos favoritos y cabe entero en el plan, sin cambiarle nada.",
 ing:[{i:"Pechuga de pollo",a:160,b:190,u:"g"},{i:"Plátano maduro",a:0.5,b:0.75,u:"und"},
      {i:"Aguacate",a:0.5,b:0.5,u:"und"},{i:"Dientes de ajo",a:3,b:3,u:"und"},
      {i:"Tamari",a:1,b:1,u:"cda",d:1},{i:"Aceite de oliva",a:2,b:2,u:"cda"},
      {i:"Rúgula",a:1,b:1,u:"puñado"}],
 pasos:["Aceite de ajo y retira los dientes.",
        "Pechuga aplanada a golpes, cinco minutos por lado, sin moverla.",
        "En otro sartén, plátano en tajadas hasta que los bordes estén oscuros.",
        "Aguacate y rúgula en frío al lado. Tamari sobre el pollo al servir."],
 crispy:"Aplanar la pechuga la cocina parejo y dora más superficie."},

{id:"tilapia-plancha", mom:"cena", n:"Tilapia a la plancha con jengibre", min:25, base:"pescado", tag:["plancha","rápido"],
 porque:"La forma más limpia de comer pescado: alta proteína, purina baja, quince minutos.",
 ing:[{i:"Filete de tilapia",a:180,b:210,u:"g"},{i:"Jengibre en julianas",a:15,b:15,u:"g"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Tamari",a:1,b:1,u:"cda",d:1},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"},{i:"Papa criolla",a:150,b:180,u:"g"}],
 pasos:["Cocina la papa criolla y resérvala.",
        "Seca el filete muy bien. Sartén muy caliente, tres minutos sin tocarlo, voltea dos.",
        "Aparte, fríe el jengibre en julianas hasta que quede crocante.",
        "Aplasta la papa criolla y dórala en el mismo sartén. Monta con tamari y cebolla larga."],
 crispy:"El jengibre frito en julianas es el crujiente. Y la papa criolla aplastada dora mejor que entera."},

{id:"pinchos-miso", mom:"ambos", n:"Pinchos de cerdo al miso", min:35, base:"cerdo", tag:["plancha"],
 porque:"El miso te encanta y es soya fermentada, que suele caer bien aunque la legumbre entera no.",
 ing:[{i:"Lomo de cerdo en cubos",a:120,b:150,u:"g"},{i:"Miso",a:2,b:2,u:"cda",d:1},
      {i:"Miel",a:1,b:1,u:"cdta"},{i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},
      {i:"Jengibre rallado",a:10,b:10,u:"g"},{i:"Palillos de pincho",a:4,b:5,u:"und"},
      {i:"Arroz blanco crudo",a:60,b:75,u:"g"},{i:"Pepino sin piel",a:1,b:1,u:"und"}],
 pasos:["Mezcla miso, miel, vinagre y jengibre. Marina el cerdo veinte minutos.",
        "Limpia el exceso de marinada: el miso se quema fácil.",
        "Sartén-plancha caliente, tres minutos por cara.",
        "Sirve con arroz y bastones de pepino crudo."],
 crispy:"Quitar el exceso de marinada es lo que evita que se queme en vez de dorar."},

{id:"hamburguesa-pollo", mom:"almuerzo", n:"Hamburguesa de pollo teriyaki en arepa", min:40, base:"pollo", tag:["plancha"],
 porque:"Tu hamburguesa, sin el pan de trigo: la arepa de maíz nixtamalizado hace de pan y queda más crocante.",
 ing:[{i:"Pollo picado a cuchillo",a:150,b:180,u:"g"},{i:"Arepas de maíz",a:1,b:1.5,u:"und"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Tamari",a:2,b:2,u:"cda",d:1},
      {i:"Miel",a:1,b:1,u:"cdta"},{i:"Jengibre rallado",a:10,b:10,u:"g"},
      {i:"Aguacate",a:0.5,b:0.5,u:"und"},{i:"Rúgula",a:1,b:1,u:"puñado"},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Pica el pollo a cuchillo, no lo muelas: la carne molida no te cae bien y picada queda con textura.",
        "Mezcla con cebolla larga y jengibre, forma las tortas y déjalas diez minutos en la nevera para que agarren.",
        "Sartén caliente, cuatro minutos por lado sin tocarlas.",
        "Pincela tamari con miel al final. Tuesta las arepas y monta con aguacate y rúgula."],
 crispy:"Reposo en nevera antes del sartén: sin eso se desarman."},

{id:"huevos-tocineta", mom:"desayuno", n:"Huevos crocantes con tocineta y cebolla larga", min:20, base:"huevo", tag:["desayuno","rápido","seguro"],
 porque:"Tu desayuno favorito, con un toque de tamari que lo lleva al lado asiático sin cambiarlo.",
 ing:[{i:"Huevos",a:2,b:3,u:"und"},{i:"Tocineta",a:2,b:3,u:"lonjas"},
      {i:"Cebolla larga verde",a:1,b:1,u:"tallo"},{i:"Tamari",a:1,b:1,u:"cdta",d:1},
      {i:"Arepa de maíz",a:1,b:1,u:"und"},{i:"Aguacate",a:0.5,b:0.5,u:"und"}],
 pasos:["Tocineta en sartén frío, fuego medio, hasta que quede quebradiza. Sácala.",
        "En esa grasa, huevos a fuego alto: el borde tiene que encarrujarse y dorar.",
        "Tamari por encima al servir, cebolla larga cruda.",
        "Arepa tostada y aguacate al lado."],
 crispy:"Sartén frío para la tocineta y fuego alto para el huevo. Al revés no funciona ninguno de los dos.",
 ojo:"Si hay pastilla en ayunas, este desayuno va 30–60 minutos después de tomarla."},

{id:"tamagoyaki", mom:"desayuno", n:"Tortilla japonesa firme con arroz", min:25, base:"huevo", tag:["desayuno","económico"],
 porque:"El tamagoyaki tradicional queda jugoso; esta versión se cocina hasta firme, que es como lo toleras.",
 ing:[{i:"Huevos",a:3,b:4,u:"und"},{i:"Tamari",a:1,b:1,u:"cdta",d:1},
      {i:"Cebolla larga verde",a:1,b:1,u:"tallo"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Aceite de oliva",a:1,b:1,u:"cda"}],
 pasos:["Bate los huevos con el tamari y la cebolla larga picada muy fina.",
        "Sartén pequeño a fuego medio. Echa un tercio, deja cuajar del todo y enróllalo hacia ti.",
        "Repite dos veces más, enrollando sobre lo anterior.",
        "Deja que el exterior dore antes de sacarlo. Corta en rodajas gruesas."],
 crispy:"Cuajar cada capa completamente antes de enrollar. Ahí está la diferencia con el original."},

{id:"huevo-arroz-ajo", mom:"cena", n:"Huevo frito sobre arroz al aceite de ajo", min:20, base:"huevo", tag:["rápido","económico","seguro"],
 porque:"Tres ingredientes y quince minutos. El plato de los días sin ganas.",
 ing:[{i:"Huevos",a:2,b:3,u:"und"},{i:"Arroz blanco crudo",a:70,b:85,u:"g"},
      {i:"Dientes de ajo",a:5,b:5,u:"und"},{i:"Tamari",a:1,b:1,u:"cda",d:1},
      {i:"Cebolla larga verde",a:1,b:1,u:"tallo"},{i:"Aceite de oliva",a:3,b:3,u:"cda"}],
 pasos:["Cocina el arroz.",
        "Dora los dientes enteros a fuego bajo hasta dorados y retíralos.",
        "Sube el fuego y fríe los huevos en ese aceite hasta que el borde quede encajado y crocante.",
        "Arroz, tamari, huevo encima y cebolla larga."],
 crispy:"Aceite abundante y muy caliente. El borde del huevo se infla y se tuesta solo."},

{id:"tostada-cucayo", mom:"desayuno", n:"Tostada de cucayo con aguacate y huevo", min:30, base:"huevo", tag:["cucayo","desayuno"],
 porque:"El cucayo como base en vez de pan. Sin gluten y más crocante que cualquier tostada.",
 ing:[{i:"Arroz blanco cocido y frío",a:150,b:180,u:"g"},{i:"Huevos",a:2,b:2,u:"und"},
      {i:"Aguacate",a:1,b:1,u:"und"},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Tamari",a:1,b:1,u:"cda",d:1},{i:"Aceite de oliva",a:3,b:3,u:"cda"}],
 pasos:["Aprieta el arroz frío en el sartén formando una torta delgada y pareja.",
        "Fuego medio, ocho minutos sin tocarla, hasta que se despegue sola.",
        "Voltea con ayuda de un plato, cuatro minutos más.",
        "Corta en cuñas y monta aguacate aplastado, huevo frito, tamari y ajonjolí."],
 crispy:"Se despega sola cuando está lista. Si se pega, le falta tiempo."},

{id:"criolla-sesamo", mom:"acomp", n:"Papa criolla crocante con ajonjolí", min:35, base:"veg", tag:["crispy","acompañamiento"],
 porque:"Acompañamiento que resuelve el almidón y el crujiente al tiempo.",
 ing:[{i:"Papa criolla",a:200,b:240,u:"g"},{i:"Ajonjolí",a:2,b:2,u:"cda"},
      {i:"Tamari",a:1,b:1,u:"cda",d:1},{i:"Cebolla larga verde",a:1,b:1,u:"tallo"},
      {i:"Aceite de oliva",a:3,b:3,u:"cda"}],
 pasos:["Cocina las papas enteras hasta que entren con tenedor, sin deshacerse.",
        "Escúrrelas y déjalas secar cinco minutos al aire.",
        "Aplástalas apenas, con el fondo de un vaso.",
        "Sartén caliente, dóralas por las dos caras sin moverlas. Tamari, ajonjolí y cebolla larga."],
 crispy:"Secarlas al aire antes del sartén. La papa mojada nunca dora."},

{id:"yuca-ajo", mom:"acomp", n:"Yuca en bastones al aceite de ajo", min:40, base:"veg", tag:["crispy","acompañamiento"],
 porque:"Tubérculo que toleras bien, sin gluten, y en textura de papa a la francesa.",
 ing:[{i:"Yuca",a:250,b:300,u:"g"},{i:"Dientes de ajo",a:5,b:5,u:"und"},
      {i:"Aceite de oliva",a:4,b:4,u:"cda"},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Tamari",a:1,b:1,u:"cda",d:1}],
 pasos:["Cocina la yuca en bastones hasta que empiece a abrirse. Escurre y seca bien.",
        "Dora los dientes en el aceite y retíralos.",
        "Fríe los bastones en ese aceite, sin amontonar, hasta que estén dorados por todos lados.",
        "Tamari y ajonjolí al sacarlos."],
 crispy:"Cocida primero y bien seca después. Cruda al aceite queda dura por dentro."},

{id:"maiz-mani", mom:"acomp", n:"Maíz salteado con maní", min:20, base:"veg", tag:["rápido","acompañamiento","económico"],
 porque:"Dulce natural sin azúcar libre, y dos texturas crujientes en un acompañamiento de quince minutos.",
 ing:[{i:"Maíz tierno desgranado",a:200,b:240,u:"g"},{i:"Maní tostado",a:30,b:35,u:"g"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Tamari",a:1,b:1,u:"cda",d:1},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Sartén muy caliente, maíz en capa delgada, tres minutos sin mover hasta que algunos granos se tuesten.",
        "Revuelve, otros dos minutos.",
        "Fuera del fuego: tamari, maní y cebolla larga."],
 crispy:"Los granos tostados son el punto. Si revuelves todo el tiempo, solo se calienta."},

{id:"pepino-machacado", mom:"acomp", n:"Pepino machacado con vinagre de arroz", min:15, base:"veg", tag:["rápido","acompañamiento","calor"],
 porque:"El banchan más fácil que existe. Fresco sin ser húmedo, porque el pepino se escurre.",
 ing:[{i:"Pepino sin piel ni semillas",a:2,b:2,u:"und"},{i:"Vinagre de arroz",a:2,b:2,u:"cda",d:1},
      {i:"Aceite de ajonjolí",a:1,b:1,u:"cdta",d:1},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Tamari",a:1,b:1,u:"cdta",d:1},{i:"Sal",a:1,b:1,u:"cdta"}],
 pasos:["Machaca el pepino con el costado del cuchillo y pártelo en trozos irregulares.",
        "Sálalo y déjalo diez minutos en un colador. Va a soltar bastante agua.",
        "Escurre y aprieta con la mano.",
        "Vinagre, tamari, aceite de ajonjolí y ajonjolí. Sirve de una."],
 crispy:"Los diez minutos en el colador son la receta entera. Sin eso queda aguado."},

{id:"zanahoria-apio", mom:"acomp", n:"Zanahoria y apio en juliana con ajonjolí", min:15, base:"veg", tag:["rápido","acompañamiento","crudo"],
 porque:"Crudos, que es como mejor los toleras, y el acompañamiento más rápido de la carta.",
 ing:[{i:"Zanahoria",a:2,b:2,u:"und"},{i:"Apio",a:3,b:3,u:"tallos"},
      {i:"Vinagre de arroz",a:2,b:2,u:"cda",d:1},{i:"Aceite de ajonjolí",a:1,b:1,u:"cdta",d:1},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Miel",a:1,b:1,u:"cdta"}],
 pasos:["Corta todo en julianas finas y parejas.",
        "Mezcla vinagre, miel y aceite de ajonjolí.",
        "Revuelve justo antes de servir, no antes.",
        "Ajonjolí tostado encima."],
 crispy:"Aliñar al momento. Media hora antes y el vinagre lo ablanda todo."},

{id:"espinaca-sesamo", mom:"acomp", n:"Espinaca al ajonjolí estilo namul", min:15, base:"veg", tag:["rápido","acompañamiento"],
 porque:"Folato y nitratos. Las purinas vegetales no cuentan como las animales, así que la espinaca se queda.",
 ing:[{i:"Espinaca",a:250,b:250,u:"g"},{i:"Ajonjolí",a:2,b:2,u:"cda"},
      {i:"Aceite de ajonjolí",a:1,b:1,u:"cda",d:1},{i:"Tamari",a:1,b:1,u:"cda",d:1},
      {i:"Dientes de ajo",a:2,b:2,u:"und"},{i:"Aceite de oliva",a:1,b:1,u:"cda"}],
 pasos:["Sumerge la espinaca en agua hirviendo treinta segundos y pásala a agua fría.",
        "Escúrrela apretando con las manos hasta que no suelte nada. Esto es lo importante.",
        "Dora el ajo en el aceite, retíralo.",
        "Mezcla la espinaca con ese aceite, tamari, aceite de ajonjolí y ajonjolí machacado."],
 crispy:"Apretar la espinaca hasta que quede seca. Mojada es justo la textura que no toleras."}

,
{id:"onigiri-atun", mom:"almuerzo", n:"Onigiri de atún aderezado", min:35, base:"pescado", tag:["arroz","fiambre"],
 porque:"Lo que ya les encanta. El atún enlatado bien aderezado deja de saber a enlatado, y el arroz hace el resto.",
 ing:[{i:"Arroz blanco crudo",a:90,b:100,u:"g"},{i:"Atún enlatado en agua, escurrido",a:120,b:90,u:"g"},
      {i:"Ajonjolí",a:2,b:2,u:"cda"},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Tamari",a:1,b:1,u:"cda",d:1},{i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},
      {i:"Miel",a:1,b:1,u:"cdta"},{i:"Alga nori en láminas",a:2,b:2,u:"und",d:1},
      {i:"Aguacate",a:0.5,b:0.5,u:"und"}],
 pasos:["Cocina el arroz con un poco más de agua de lo normal, para que quede pegajoso y se deje moldear.",
        "Escurre el atún apretándolo hasta que no suelte nada, y dóralo dos minutos en sartén seco.",
        "Mézclalo con tamari, vinagre, miel, ajonjolí y la cebolla larga picada fina.",
        "Con el arroz tibio y las manos húmedas, arma triángulos apretados con el relleno en el centro.",
        "Envuelve la base con una tira de nori justo antes de comer."],
 crispy:"El nori se pone al final. Puesto antes, se humedece con el arroz y pierde la textura.",
 ojo:"Porción de atún al revés que en el resto de la carta: más grande para la A, más corta para la B."},

{id:"atun-sellado", mom:"cena", n:"Atún fresco sellado con ajonjolí", min:25, base:"pescado", tag:["plancha","rápido"],
 porque:"Atún fresco, que es distinto al enlatado en todo. Se sella por fuera y queda rosado por dentro: nada de textura blanda.",
 ing:[{i:"Lomo de atún fresco",a:170,b:150,u:"g"},{i:"Ajonjolí",a:3,b:3,u:"cda"},
      {i:"Tamari",a:2,b:2,u:"cda",d:1},{i:"Jengibre rallado",a:10,b:10,u:"g"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Aceite de oliva",a:2,b:2,u:"cda"},
      {i:"Arroz blanco crudo",a:60,b:80,u:"g"},{i:"Pepino sin piel",a:1,b:1,u:"und"}],
 pasos:["Seca el lomo y presiónalo contra el ajonjolí por todas las caras hasta que quede cubierto.",
        "Sartén muy caliente con poco aceite. Sella cuarenta segundos por cara, no más.",
        "Saca y corta en láminas gruesas con cuchillo bien afilado.",
        "Tamari con jengibre al lado para untar, no encima. Arroz y bastones de pepino."],
 crispy:"La costra es el ajonjolí tostado. Cuarenta segundos por cara: pasado de punto queda seco y harinoso.",
 ojo:"Atún fresco es alto en purinas: porción más corta para la B y máximo una vez por semana."},

{id:"pollo-panela", mom:"ambos", n:"Pollo con panela y jengibre", min:30, base:"pollo", tag:["sartén","sin despensa"],
 porque:"Sabor agridulce con panela, que ya está en la cocina. No necesita comprar nada nuevo.",
 ing:[{i:"Pechuga en tiras",a:150,b:180,u:"g"},{i:"Panela raspada",a:1,b:1,u:"cda"},
      {i:"Jengibre rallado",a:15,b:15,u:"g"},{i:"Dientes de ajo",a:3,b:3,u:"und"},
      {i:"Vinagre blanco",a:1,b:1,u:"cda"},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Aceite de oliva",a:2,b:2,u:"cda"},
      {i:"Arroz blanco crudo",a:60,b:75,u:"g"},{i:"Sal",a:1,b:1,u:"pizca"}],
 pasos:["Aceite de ajo: dora los dientes enteros y retíralos.",
        "Pollo seco y salado a fuego alto, dos minutos sin moverlo, voltea y dos más.",
        "Baja el fuego. Panela, jengibre y vinagre: se derrite y glasea en un minuto.",
        "Cebolla larga y ajonjolí fuera del fuego."],
 crispy:"La panela glasea, no moja. Si queda líquido, súbele el fuego treinta segundos."},

{id:"criolla-huevo-jengibre", mom:"cena", n:"Papa criolla con huevo y jengibre", min:30, base:"huevo", tag:["sartén","sin despensa","económico"],
 porque:"Papa criolla, huevo y jengibre: todo de la tienda de la esquina, con el sabor moviéndose hacia el lado asiático sin comprar nada.",
 ing:[{i:"Papa criolla",a:200,b:230,u:"g"},{i:"Huevos",a:2,b:3,u:"und"},
      {i:"Jengibre en julianas",a:15,b:15,u:"g"},{i:"Dientes de ajo",a:4,b:4,u:"und"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Aceite de oliva",a:3,b:3,u:"cda"},{i:"Sal",a:1,b:1,u:"pizca"}],
 pasos:["Cocina la papa criolla entera, escúrrela y déjala secar cinco minutos al aire.",
        "Dora el ajo en el aceite y retíralo. Fríe el jengibre en julianas hasta que quede crocante y sácalo también.",
        "Aplasta las papas apenas y dóralas en ese aceite por las dos caras.",
        "Huevos aparte, a fuego alto, con el borde encarrujado. Monta papa, huevo, jengibre crocante, cebolla larga y ajonjolí."],
 crispy:"Dos crocantes distintos: la papa aplastada y el jengibre frito. El jengibre frito reemplaza cualquier salsa."}

,
{id:"pollo-ajonjoli", mom:"almuerzo", n:"Pollo en costra de ajonjolí", min:30, base:"pollo", tag:["sartén","sin despensa","crispy"],
 porque:"El ajonjolí tostado hace la costra y el sabor, sin necesidad de ninguna salsa.",
 ing:[{i:"Pechuga en filetes delgados",a:160,b:190,u:"g"},{i:"Ajonjolí",a:4,b:4,u:"cda"},
      {i:"Maizena",a:2,b:2,u:"cda"},{i:"Dientes de ajo",a:3,b:3,u:"und"},{i:"Jengibre rallado",a:10,b:10,u:"g"},
      {i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:3,b:3,u:"cda"},{i:"Arroz blanco crudo",a:70,b:85,u:"g"},
      {i:"Rúgula",a:1,b:1,u:"puñado"}],
 pasos:["Aplana los filetes a golpes, sálalos y frótalos con el jengibre.",
        "Mezcla Maizena y ajonjolí en un plato y presiona cada filete por las dos caras.",
        "Aceite de ajo: dora los dientes y retíralos.",
        "Filetes a fuego medio-alto, cuatro minutos por cara, sin moverlos.",
        "Arroz y rúgula cruda al lado."],
 crispy:"Maizena y ajonjolí juntos: la Maizena pega y el ajonjolí tuesta."},

{id:"arroz-pollo-larga", mom:"almuerzo", n:"Arroz con pollo desmechado y cebolla larga", min:40, base:"pollo", tag:["sartén","sin despensa","económico"],
 porque:"El arroz con pollo de siempre, pero salteado a fuego alto para que quede suelto y con bordes tostados.",
 ing:[{i:"Pechuga cocida y desmechada",a:150,b:180,u:"g"},{i:"Arroz blanco cocido y frío",a:180,b:220,u:"g"},
      {i:"Cebolla larga verde",a:4,b:4,u:"tallos"},{i:"Zanahoria en cubitos",a:1,b:1,u:"und"},
      {i:"Maíz tierno",a:80,b:80,u:"g"},{i:"Dientes de ajo",a:4,b:4,u:"und"},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:3,b:3,u:"cda"}],
 pasos:["Aceite de ajo, retira los dientes.",
        "Zanahoria y maíz a fuego alto, tres minutos, hasta que algunos granos se tuesten.",
        "Pollo desmechado, dos minutos, hasta que las hebras doren.",
        "Arroz frío extendido, dos minutos quieto. Sal, cebolla larga y ajonjolí fuera del fuego."],
 crispy:"El arroz tiene que estar frío. Tibio se apelmaza y queda mazacote."},
{id:"platano-ajonjoli", mom:"acomp", n:"Plátano maduro dorado con ajonjolí", min:20, base:"veg", tag:["acompañamiento","sin despensa","rápido"],
 porque:"Dulce natural, potasio y un acompañamiento que le va a casi todo lo de la carta.",
 ing:[{i:"Plátano maduro",a:1,b:1.5,u:"und"},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Aceite de oliva",a:1,b:1,u:"cda"},{i:"Sal",a:1,b:1,u:"pizca"}],
 pasos:["Corta el plátano en tajadas gruesas y en diagonal, que dan más superficie.",
        "Sartén a fuego medio, sin amontonar, hasta que los bordes estén oscuros.",
        "Voltea una sola vez.",
        "Pizca de sal y ajonjolí al sacarlas."],
 crispy:"Fuego medio, no alto: alto quema el azúcar antes de que el centro se ablande."},

{id:"pechuga-maizena", mom:"almuerzo", n:"Pechuga crocante en Maizena", min:30, base:"pollo", tag:["crispy","sin despensa"],
 porque:"La Maizena da una costra fina y seca que aguanta mejor que el apanado de pan, y además no lleva trigo.",
 ing:[{i:"Pechuga en filetes",a:160,b:190,u:"g"},{i:"Maizena",a:4,b:4,u:"cda"},
      {i:"Huevos",a:1,b:1,u:"und"},{i:"Ajo en polvo",a:1,b:1,u:"cdta"},
      {i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:4,b:4,u:"cda"},
      {i:"Papa criolla",a:180,b:210,u:"g"},{i:"Pepino sin piel",a:1,b:1,u:"und"}],
 pasos:["Cocina la papa criolla y resérvala.",
        "Aplana los filetes, sálalos y mézclales el ajo en polvo.",
        "Pásalos por huevo batido y luego por Maizena, apretando bien.",
        "Sartén con aceite a fuego medio-alto, cuatro minutos por cara, sin tocarlos.",
        "Saca sobre rejilla. Dora la papa criolla aplastada en el mismo sartén."],
 crispy:"Rejilla, nunca papel: el vapor de abajo ablanda la costra en un minuto."},

{id:"res-tomate", mom:"almuerzo", n:"Carne desmechada con tomate y cebolla larga", min:40, base:"res", tag:["sartén","sin despensa"],
 porque:"La carne desmechada de siempre, con el tomate cocido que aporta licopeno. Porción medida.",
 ing:[{i:"Carne de res para desmechar (ya cocida)",a:120,b:145,u:"g"},{i:"Tomate maduro",a:2,b:2,u:"und"},
      {i:"Cebolla larga verde",a:3,b:3,u:"tallos"},{i:"Dientes de ajo",a:4,b:4,u:"und"},
      {i:"Comino",a:1,b:1,u:"pizca"},{i:"Sal",a:1,b:1,u:"pizca"},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"},
      {i:"Plátano maduro",a:0.5,b:0.75,u:"und"}],
 pasos:["Aceite de ajo, retira los dientes.",
        "Carne desmechada a fuego alto, tres minutos sin mover, hasta que las hebras se tuesten.",
        "Tomate despepitado en cubos, dos minutos, solo hasta que suelte y evapore.",
        "Sal, comino y cebolla larga fuera del fuego. Arroz y tajadas al lado."],
 crispy:"Las hebras tostadas primero, el tomate después. Al revés queda guiso húmedo.",
 ojo:"Res una vez por semana como máximo."},

{id:"tilapia-panela", mom:"cena", n:"Tilapia dorada con panela y jengibre", min:25, base:"pescado", tag:["plancha","sin despensa","rápido"],
 porque:"Agridulce con panela, que ya está en la cocina. Pescado suave y proteína alta sin nada de despensa.",
 ing:[{i:"Filete de tilapia",a:180,b:210,u:"g"},{i:"Panela raspada",a:1,b:1,u:"cda"},
      {i:"Jengibre rallado",a:15,b:15,u:"g"},{i:"Vinagre blanco",a:1,b:1,u:"cda"},
      {i:"Ajonjolí",a:2,b:2,u:"cda"},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:2,b:2,u:"cda"},
      {i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Seca el filete muy bien y sálalo.",
        "Sartén muy caliente, tres minutos sin tocarlo, voltea dos.",
        "Fuego bajo: panela, jengibre y vinagre. Glasea un minuto bañando el pescado.",
        "Ajonjolí y cebolla larga al servir."],
 crispy:"Filete seco y sartén muy caliente. Húmedo se pega y se rompe al voltear."},

{id:"arroz-huevo-aguacate", mom:"cena", n:"Arroz con huevo y aguacate", min:20, base:"huevo", tag:["rápido","sin despensa","económico","seguro"],
 porque:"La cena de los días sin ganas: quince minutos y tres ingredientes que siempre hay.",
 ing:[{i:"Arroz blanco crudo",a:70,b:85,u:"g"},{i:"Huevos",a:2,b:3,u:"und"},
      {i:"Aguacate",a:0.5,b:0.75,u:"und"},{i:"Cebolla larga verde",a:1,b:1,u:"tallo"},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:3,b:3,u:"cda"}],
 pasos:["Cocina el arroz.",
        "Aceite bien caliente y abundante; fríe los huevos hasta que el borde se encarruje.",
        "Arroz, huevo encima, sal.",
        "Aguacate, cebolla larga y ajonjolí."],
 crispy:"Aceite abundante y muy caliente: el borde del huevo se infla y se tuesta solo."},

{id:"criolla-tibia", mom:"cena", n:"Papa criolla tibia con huevo y ajonjolí", min:30, base:"huevo", tag:["sin despensa","económico"],
 porque:"Cena liviana que no es ensalada fría ni nada húmedo: papa tibia, huevo firme y ajonjolí.",
 ing:[{i:"Papa criolla",a:200,b:230,u:"g"},{i:"Huevos",a:2,b:2,u:"und"},
      {i:"Apio en cubitos",a:2,b:2,u:"tallos"},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Ajonjolí",a:2,b:2,u:"cda"},{i:"Vinagre blanco",a:1,b:1,u:"cda"},
      {i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Cocina la papa criolla hasta que entre con tenedor y escúrrela bien.",
        "Cuece los huevos doce minutos, que la yema quede firme del todo. Pícalos en cuartos.",
        "Aplasta las papas apenas y dóralas en el sartén por las dos caras.",
        "Mezcla tibio con apio crudo, vinagre, sal, cebolla larga y ajonjolí."],
 crispy:"El apio entra crudo al final: es el único crujiente del plato."},

{id:"pinchos-panela", mom:"almuerzo", n:"Pinchos de pollo con panela y ajo", min:35, base:"pollo", tag:["plancha","sin despensa"],
 porque:"Los pinchos de siempre, glaseados con panela en vez de salsa comprada.",
 ing:[{i:"Muslo de pollo en cubos",a:160,b:190,u:"g"},{i:"Panela raspada",a:2,b:2,u:"cda"},
      {i:"Dientes de ajo",a:4,b:4,u:"und"},{i:"Vinagre blanco",a:1,b:1,u:"cda"},
      {i:"Cebolla larga",a:3,b:3,u:"tallos"},{i:"Palillos de pincho",a:4,b:5,u:"und"},
      {i:"Sal",a:1,b:1,u:"pizca"},{i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Arma los pinchos alternando pollo y trozos de cebolla larga. Sálalos.",
        "Aceite de ajo en el sartén-plancha; retira los dientes.",
        "Tres minutos por cara a fuego medio-alto.",
        "Disuelve la panela con el vinagre y pincela en los últimos dos minutos."],
 crispy:"El glaseado va al final. Desde el principio, la panela se quema antes de que el pollo esté."},

{id:"tortilla-papa", mom:"cena", n:"Tortilla firme de papa y cebolla larga", min:35, base:"huevo", tag:["sin despensa","económico"],
 porque:"Se cocina hasta firme por dentro, nada de centro jugoso. Sirve igual de cena o de desayuno del día siguiente.",
 ing:[{i:"Papa",a:250,b:280,u:"g"},{i:"Huevos",a:3,b:4,u:"und"},
      {i:"Cebolla larga verde",a:3,b:3,u:"tallos"},{i:"Sal",a:1,b:1,u:"cdta"},
      {i:"Aceite de oliva",a:4,b:4,u:"cda"},{i:"Rúgula",a:1,b:1,u:"puñado"}],
 pasos:["Corta la papa en láminas finas y dórala en el aceite a fuego medio, doce minutos, removiendo poco.",
        "Escurre el aceite sobrante y mézclala con los huevos batidos, la sal y la cebolla larga.",
        "Devuelve al sartén a fuego medio-bajo, ocho minutos.",
        "Voltea con un plato y otros seis minutos, hasta que el centro esté cuajado del todo."],
 crispy:"Los bordes dorados son el punto. El centro tiene que quedar firme, no baboso."},

{id:"huevo-platano", mom:"desayuno", n:"Huevo frito con plátano maduro y aguacate", min:20, base:"huevo", tag:["desayuno","rápido","sin despensa","seguro"],
 porque:"Tres cosas que siempre hay en la cocina, con el dulce del plátano haciendo de contraste.",
 ing:[{i:"Huevos",a:2,b:3,u:"und"},{i:"Plátano maduro",a:0.5,b:0.75,u:"und"},
      {i:"Aguacate",a:0.5,b:0.5,u:"und"},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Tajadas de plátano en diagonal, fuego medio, hasta que los bordes estén oscuros. Sácalas.",
        "Sube el fuego y fríe los huevos en el mismo sartén hasta que el borde encarruje.",
        "Monta plátano, huevo, aguacate, sal y ajonjolí."],
 crispy:"El mismo sartén para las dos cosas: el azúcar que suelta el plátano tuesta el borde del huevo."},

{id:"maiz-ajonjoli", mom:"acomp", n:"Maíz tostado con maní y ajonjolí", min:20, base:"veg", tag:["acompañamiento","rápido","sin despensa","económico"],
 porque:"Dos crujientes y dulce natural, sin azúcar añadido y sin nada de despensa.",
 ing:[{i:"Maíz tierno desgranado",a:200,b:240,u:"g"},{i:"Maní tostado",a:30,b:35,u:"g"},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Sartén muy caliente, maíz en capa delgada, tres minutos sin mover.",
        "Revuelve y dale dos minutos más, hasta que varios granos estén tostados.",
        "Fuera del fuego: sal, maní, ajonjolí y cebolla larga."],
 crispy:"Capa delgada y quieta. Revolviendo todo el tiempo solo se calienta."},

{id:"remolacha-ajonjoli", mom:"acomp", n:"Remolacha rallada con ajonjolí", min:15, base:"veg", tag:["acompañamiento","rápido","crudo","sin despensa"],
 porque:"Nitratos y color, cruda para que quede firme. De los vegetales que mejor toleras.",
 ing:[{i:"Remolacha cruda",a:2,b:2,u:"und"},{i:"Zanahoria",a:1,b:1,u:"und"},
      {i:"Ajonjolí",a:2,b:2,u:"cda"},{i:"Vinagre blanco",a:1,b:1,u:"cda"},
      {i:"Miel",a:1,b:1,u:"cdta"},{i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:1,b:1,u:"cda"}],
 pasos:["Ralla la remolacha y la zanahoria grueso, no fino.",
        "Mezcla vinagre, miel, aceite y sal.",
        "Aliña justo antes de servir, no antes.",
        "Ajonjolí tostado encima."],
 crispy:"Rallado grueso y aliñado al momento. Fino y con tiempo, se ablanda y suelta agua."},

{id:"pollo-zanahoria", mom:"cena", n:"Pollo con zanahoria y jengibre", min:25, base:"pollo", tag:["sartén","rápido","sin despensa"],
 porque:"Cena liviana de veinte minutos, con la zanahoria firme y el jengibre haciendo todo el trabajo.",
 ing:[{i:"Pechuga en tiras",a:150,b:180,u:"g"},{i:"Zanahoria en bastones",a:2,b:2,u:"und"},
      {i:"Jengibre rallado",a:15,b:15,u:"g"},{i:"Dientes de ajo",a:3,b:3,u:"und"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Vinagre blanco",a:1,b:1,u:"cdta"},{i:"Sal",a:1,b:1,u:"pizca"},
      {i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Aceite de ajo, retira los dientes.",
        "Pollo seco y salado a fuego alto, dos minutos sin mover, voltea y dos más.",
        "Zanahoria y jengibre, dos minutos: tiene que sonar al morderla.",
        "Vinagre, cebolla larga y ajonjolí fuera del fuego."],
 crispy:"La zanahoria entra de última y sale firme. Si se ablanda, entró muy temprano."},

{id:"arepa-pastrami", mom:"almuerzo", n:"Arepa de pastrami con aguacate", min:20, base:"cerdo", tag:["rápido","sin despensa"],
 porque:"Tu sánduche favorito sobre arepa de maíz en vez de pan, que además queda más crocante.",
 ing:[{i:"Pastrami en lonjas",a:90,b:110,u:"g"},{i:"Arepas de maíz",a:1,b:1.5,u:"und"},
      {i:"Aguacate",a:0.5,b:0.5,u:"und"},{i:"Tomate maduro",a:1,b:1,u:"und"},
      {i:"Rúgula",a:1,b:1,u:"puñado"},{i:"Ajonjolí",a:1,b:1,u:"cda"}],
 pasos:["Tuesta las arepas en sartén seco hasta que suenen huecas al golpearlas.",
        "Dora el pastrami sin aceite hasta que los bordes se ricen.",
        "Abre la arepa, unta el aguacate aplastado.",
        "Pastrami, tomate en rodajas finas, rúgula y ajonjolí."],
 crispy:"Los bordes rizados del pastrami y la arepa bien tostada. Nada de arepa blanda.",
 ojo:"Embutido curado: alto en sodio y en purinas. Una vez por semana."},

{id:"cerdo-panela", mom:"almuerzo", n:"Cerdo agridulce de panela y vinagre", min:30, base:"cerdo", tag:["sartén","sin despensa"],
 porque:"Agridulce con lo que hay en la alacena colombiana. Porción de cerdo corta, como siempre.",
 ing:[{i:"Lomo de cerdo en cubos",a:120,b:150,u:"g"},{i:"Panela raspada",a:2,b:2,u:"cda"},
      {i:"Vinagre blanco",a:2,b:2,u:"cda"},{i:"Maizena",a:2,b:2,u:"cda"},
      {i:"Zanahoria en bastones",a:1,b:1,u:"und"},{i:"Jengibre rallado",a:10,b:10,u:"g"},
      {i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:2,b:2,u:"cda"},
      {i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Pasa los cubos de cerdo por Maizena y sal.",
        "Fuego alto, tres minutos sin mover, hasta que doren.",
        "Zanahoria, dos minutos.",
        "Panela, vinagre y jengibre; un minuto de fuego hasta que brille y espese."],
 crispy:"La Maizena de la carne es la que espesa la salsa. No hace falta nada más."},

{id:"pollo-miso", mom:"cena", n:"Pollo al miso con ajonjolí", min:30, base:"pollo", tag:["sartén"],
 porque:"El miso te encanta y aquí carga todo el plato. Soya fermentada, que suele caer mejor que la legumbre entera.",
 ing:[{i:"Pechuga en tiras",a:150,b:180,u:"g"},{i:"Miso",a:2,b:2,u:"cda",d:1},
      {i:"Miel",a:1,b:1,u:"cdta"},{i:"Vinagre de arroz",a:1,b:1,u:"cda",d:1},
      {i:"Jengibre rallado",a:10,b:10,u:"g"},{i:"Espinaca",a:120,b:120,u:"g"},
      {i:"Ajonjolí",a:2,b:2,u:"cda"},{i:"Aceite de oliva",a:2,b:2,u:"cda"},
      {i:"Arroz blanco crudo",a:60,b:75,u:"g"}],
 pasos:["Mezcla miso, miel, vinagre y jengibre en un pocillo.",
        "Pollo a fuego alto, dos minutos sin mover, voltea y dos más.",
        "Espinaca de golpe, treinta segundos.",
        "Apaga el fuego y solo entonces echa la mezcla de miso: hervido se amarga."],
 crispy:"El miso nunca hierve. Entra con el fuego apagado."},

{id:"fideos-huevo-espinaca", mom:"cena", n:"Fideos con huevo y espinaca", min:25, base:"huevo", tag:["fideos","rápido","económico"],
 porque:"Cena de veinticinco minutos, barata, y con la espinaca entrando al final para que no suelte agua.",
 ing:[{i:"Fideos de arroz",a:70,b:90,u:"g",d:1},{i:"Huevos",a:2,b:3,u:"und"},
      {i:"Espinaca",a:120,b:120,u:"g"},{i:"Dientes de ajo",a:3,b:3,u:"und"},
      {i:"Tamari",a:2,b:2,u:"cda",d:1},{i:"Ajonjolí",a:1,b:1,u:"cda"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Hidrata los fideos y escúrrelos hasta que no goteen.",
        "Aceite de ajo, retira los dientes. Cuaja los huevos firmes y sácalos.",
        "Fideos extendidos, dos minutos sin mover para que se tuesten por debajo.",
        "Devuelve el huevo, tamari por el borde, espinaca treinta segundos, ajonjolí y cebolla larga."],
 crispy:"Fideos escurridos y quietos. Mojados se vuelven engrudo."},

{id:"onigiri-pollo", mom:"almuerzo", n:"Onigiri de pollo desmechado", min:35, base:"pollo", tag:["arroz","fiambre"],
 porque:"La versión de pollo del que ya les gusta, y la única receta de la carta que viaja bien en una lonchera.",
 ing:[{i:"Arroz blanco crudo",a:90,b:110,u:"g"},{i:"Pechuga cocida y desmechada",a:130,b:160,u:"g"},
      {i:"Tamari",a:1,b:1,u:"cda",d:1},{i:"Miel",a:1,b:1,u:"cdta"},
      {i:"Jengibre rallado",a:10,b:10,u:"g"},{i:"Ajonjolí",a:2,b:2,u:"cda"},
      {i:"Cebolla larga verde",a:2,b:2,u:"tallos"},{i:"Alga nori en láminas",a:2,b:2,u:"und",d:1}],
 pasos:["Cocina el arroz con un poco más de agua para que se deje moldear.",
        "Saltea el pollo desmechado hasta que las hebras se tuesten.",
        "Fuera del fuego: tamari, miel, jengibre, ajonjolí y cebolla larga.",
        "Con las manos húmedas, arma triángulos apretados con el relleno al centro.",
        "Nori en la base, justo antes de comer."],
 crispy:"El nori se pone al final o se humedece y pierde la textura."},

{id:"robalo-jengibre", mom:"cena", n:"Róbalo a la plancha con jengibre crocante", min:25, base:"pescado", tag:["plancha","rápido"],
 porque:"Róbalo es suave y de purina baja. El jengibre frito reemplaza cualquier salsa.",
 ing:[{i:"Filete de róbalo",a:180,b:210,u:"g"},{i:"Jengibre en julianas",a:20,b:20,u:"g"},
      {i:"Tamari",a:1,b:1,u:"cda",d:1},{i:"Cebolla larga verde",a:2,b:2,u:"tallos"},
      {i:"Ajonjolí",a:1,b:1,u:"cda"},{i:"Sal",a:1,b:1,u:"pizca"},
      {i:"Aceite de oliva",a:3,b:3,u:"cda"},{i:"Papa criolla",a:150,b:180,u:"g"}],
 pasos:["Cocina la papa criolla y resérvala.",
        "Fríe el jengibre en julianas hasta que quede dorado y crocante. Sácalo a un papel.",
        "Seca el filete, sálalo, y sella tres minutos por el lado liso y dos por el otro.",
        "Dora la papa aplastada en el mismo sartén. Monta con tamari, jengibre crocante, cebolla larga y ajonjolí."],
 crispy:"El jengibre frito es el plato. Sácalo apenas dore o amarga."},

{id:"espinaca-ajo", mom:"acomp", n:"Espinaca al ajo con ajonjolí", min:15, base:"veg", tag:["acompañamiento","rápido","sin despensa"],
 porque:"Folato, nitratos y quince minutos. La versión sin nada de despensa del acompañamiento verde.",
 ing:[{i:"Espinaca",a:250,b:250,u:"g"},{i:"Dientes de ajo",a:4,b:4,u:"und"},
      {i:"Ajonjolí",a:2,b:2,u:"cda"},{i:"Vinagre blanco",a:1,b:1,u:"cdta"},
      {i:"Sal",a:1,b:1,u:"pizca"},{i:"Aceite de oliva",a:2,b:2,u:"cda"}],
 pasos:["Dora los dientes de ajo enteros en el aceite y retíralos.",
        "Espinaca de golpe a fuego alto, cuarenta segundos.",
        "Sácala y escúrrela apretando: tiene que quedar seca.",
        "Sal, vinagre y ajonjolí machacado."],
 crispy:"Escurrir apretando. Mojada es justo la textura que no toleras."}
];